apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "singbox.fullname" . }}
  labels:
    {{- include "singbox.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "singbox.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "singbox.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: sing-box
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - run
            - -C
            - /etc/sing-box
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/sing-box
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "singbox.fullname" . }}-config

