apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .values.container.appname }}
  namespace: {{ .values.container.ns }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .values.container.appname }}
  template:
    metadata:
      labels:
        app: {{ .values.container.appname }}
    spec:
      containers:
      - name: {{ .values.container.appname }}
        image: {{ .values.container.image }}
        ports:
        - containerPort: {{ .values.container.ports.port1 }}
        - containerPort: {{ .values.container.ports.port2 }}
        args: {{ .Values.container.args}}
        volumeMounts:
          - name: {{ .values.container.config.name }}
            mountPath: {{ .values.container.vol.path }}
            subPath: {{ .values.container.vol.subpath }}
        resources:
          requests:
            cpu: {{ .Values.container.resource.cpureq}}
            memory: {{ .Values.container.resource.memreq}}
          limits:
            cpu: {{ .Values.container.resource.cpulimit}}
            memory: {{ .Values.container.resource.memlimit}}
      volumes:
      - name: {{ .values.container.config.name }}
        configMap:
          name: {{ .values.container.config.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name1 }}
  namespace: {{ .values.container.ns }}
spec:
  selector:
    app: {{ .values.container.appname }}
  ports:
  - name: {{ .Values.service.ports.name1 }}
    protocol: {{ .Values.service.proto }}
    port: {{ .values.container.ports.port1 }}
    targetPort: {{ .values.container.ports.port1 }}
  type: {{ .values.service.network.type1 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .values.container.appname }}
  namespace: {{ .values.container.ns }}
spec:
  selector:
    app: {{ .values.container.appname }}
  ports:
  - name: {{ .Values.service.ports.name2 }}
    protocol: {{ .Values.service.proto }}
    port: {{ .values.container.ports.port2 }}
    targetPort: {{ .values.container.ports.port2 }}
  type: {{ .values.service.network.type2 }}