apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{- toYaml .Values.service.port | nindent 12 }}
      targetPort: {{- toYaml .Values.service.port | nindent 18 }}
      protocol: {{- toYaml .Values.service.protocol | nindent 16 }}
  selector:
    {{- toYaml .Values.labels | nindent 4 }}

