apiVersion: v1
kind: ConfigMap
metadata:
  name: singbox-config
  namespace: ali
data:
  config.json: |
    {
      "inbounds": [
        {
            "type": "vless",
            "tag": "vless-in",
            "listen": "0.0.0.0",
            "listen_port": 9000,
            "users": [
                {
                "name": "test",
                "uuid": "bf000d23-0752-40b4-affe-68f7707a9661"
                }
            ]
        },
        {
          "type": "http",
          "tag": "http-in",
          "listen": "0.0.0.0",
          "listen_port": 8080
        },
      ]
    }, 
      "outbounds": [
        {
          "type": "direct"
        }
      ],
        "log": {
        "disabled": false,
        "level": "info",
        "output": "stdout",
        "timestamp": true
        }
    }  
  
