apiVersion: v1
kind: ConfigMap
metadata:
  name: intellare
  namespace: matin
data:
  cs-1-6: |
      hostname "intellare"
      sv_name "intellare"
      #sv_password "SERVERPASSWORD"
      rcon_password "intellare"
      maxplayers "32"
      mp_autocrosshair "0"
      mp_autokick "0"
      mp_autoteambalance "0"
      mp_buytime "0.25"
      mp_c4timer "35"
      mp_chattime "5"
      mp_consistency "1"
      mp_decals "300"
      mp_fadetoblack "0"
      mp_flashlight "1"
      mp_footsteps "1"
      mp_forcecamera "3"
      mp_forcechasecam "3"
      mp_freezetime "3"
      mp_friendlyfire "0"
      mp_hostagepenalty "0"
      mp_kickpercent "1"
      mp_limitteams "0"
      mp_logdetail "3"
      mp_logecho "1"
      mp_logfile "1"
      mp_logmessages "1"
      mp_mapvoteratio "1"
      mp_maxrounds "0"
      mp_playerid "1"
      mp_roundtime "4"
      mp_startmoney "800"
      mp_timelimit "0"
      mp_tkpunish "0"
      mp_winlimit "0"
      allow_spectators "1"
      decalfrequency "60"
      edgefriction "2"
      host_framerate "0"
      log on
      pausable "1"
      pingboost "3"
      sys_ticrate "400"
      ex_interp "0.01"
      sv_accelerate "5"
      sv_aim "0"
      sv_airaccelerate "10"
      sv_airmove "1"
      sv_downloadurl "https://raw.githubusercontent.com/CajuCLC/cstrike-fastdl/main/cstrike/"
      sv_allowdownload "1"
      sv_allowupload "1"
      sv_alltalk "0"
      sv_cheats "0"
      sv_clienttrace "1"
      sv_clipmode "0"
      sv_friction "4"
      sv_gravity "800"
      sv_maxrate "25000"
      sv_minrate "2500"
      sv_maxupdaterate "101"
      sv_minupdaterate "20"
      sv_maxspeed "320"
      sv_maxunlag "0.5"
      sv_proxies "2"
      sv_restartround "0"
      sv_send_logos "0"
      sv_send_resources "1"
      sv_stepsize "18"
      sv_stopspeed "75"
      sv_timeout "65"
      sv_voiceenable "1"
      sv_wateraccelerate "10"
      sv_wateramp "0"
      sv_waterfriction "1"
      sv_unlag "1"
      sv_unlagsamples "1"
      sv_unlagpush "0"
  users: |
      ; Users configuration file
      ; File location: $moddir/addons/amxmodx/configs/users.ini

      ; Line starting with ; is a comment

      ; Access flags:
      ; a - immunity (can't be kicked/baned/slayed/slaped and affected by other commmands)
      ; b - reservation (can join on reserved slots)
      ; c - amx_kick command
      ; d - amx_ban and amx_unban commands
      ; e - amx_slay and amx_slap commands
      ; f - amx_map command
      ; g - amx_cvar command (not all cvars will be available)
      ; h - amx_cfg command
      ; i - amx_chat and other chat commands
      ; j - amx_vote and other vote commands
      ; k - access to sv_password cvar (by amx_cvar command)
      ; l - access to amx_rcon command and rcon_password cvar (by amx_cvar command)
      ; m - custom level A (for additional plugins)
      ; n - custom level B
      ; o - custom level C
      ; p - custom level D
      ; q - custom level E
      ; r - custom level F
      ; s - custom level G
      ; t - custom level H
      ; u - menu access
      ; z - user (no admin)

      ; Account flags:
      ; a - disconnect player on invalid password
      ; b - clan tag
      ; c - this is steamid/wonid
      ; d - this is ip
      ; e - password is not checked (only name/ip/steamid needed)
      ; k - name or tag is case sensitive.  eg: if you set it so the name "Ham"
      ;     is protected and case sensitive (flags "k" only), then anybody
      ;     can use the names "haM", "HAM", "ham", etc, but not "Ham"

      ; Password:
      ; Add to your autoexec.cfg: setinfo _pw "<password>"
      ; Change _pw to the value of amx_password_field

      ; Format of admin account:
      ; <name|ip|steamid> <password> <access flags> <account flags>

      ; Examples of admin accounts:
      ; "STEAM_0:0:123456" "" "abcdefghijklmnopqrstu" "ce"
      ; "123.45.67.89" "" "abcdefghijklmnopqrstu" "de"
      ; "My Name" "my_password" "abcdefghijklmnopqrstu" "a"

      "damesstos" "" "abcdefghijklmnopqrstu" ""
      "behnam" "" "abcdefghijklmnopqrstu" ""
      "mehrdad" "" "abcdefghijklmnopqrstu" ""
