---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: int-external-pool-ip
  namespace: metallb
spec:
  avoidBuggyIPs: true
  addresses:
  - 192.168.90.240-192.168.90.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: int-external-advertisement
  namespace: metallb
spec:
  ipAddressPools:
  - int-external-pool-ip
