replicaCount: 1

image:
  repository: superng6/singbox
  tag: "v1.12.0-rc.1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9090
  protocol: TCP

spec:
  template:
    metadata:
      labels:
        "app: vpn"


