replicaCount: 1

image:
  repository: superng6/singbox
  tag: "v1.12.0-rc.1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9090
  protocol: "TCP"

labels:
  app: "vpn"
  ali: "gogoli"

inbounds:
  - type: "vless"
    listen: "127.0.0.1"
    listen_port: 1080

outbounds:
  - type: "direct"

log:
  disabled: False
  level: "debug"