replicaCount: 1

image:
  repository: ghcr.io/sagernet/sing-box
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 7890
  protocol: TCP

inbounds: 
  type: "vless"
  listen: "0.0.0.0"
  listen_port: 9090

outbounds: 
  type: "direct"