apiVersion: v2
appVersion: 1.8.0-develop
dependencies:
- condition: crds.enabled
  name: crds
  repository: ""
  version: 1.8.0-develop
description: CSI Driver for dynamic provisioning of LVM Persistent Local Volumes.
home: https://openebs.io/
icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/openebs/icon/color/openebs-icon-color.png
keywords:
- cloud-native-storage
- block-storage
- filesystem
- LVM
- Local Persistent Volumes
- storage
name: lvm-localpv
sources:
- https://github.com/openebs/lvm-localpv
version: 1.8.0-develop
